name: CI / CD for Angular
on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      # Build frontend project
      - name: Build
        run: |
          cd frontend
          npm run build --prod

      # Replace secret in the frontend
      - name: Replace secret
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "{"
          tokenSuffix: "}"
          files: "frontend/src/environments/environment.prod.ts"
        env:
          SECRET_API_KEY: ${{ secrets.API_KEY}}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: frontend/dist/recipe-book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
